server:
  ip: localhost
  port: 8080
  mode: debug

database:
  driver: mysql
  host: "192.168.0.22"
  port: 3306
  username: "oth_product_code"
  password: "6HeWzEHQZSNyPnpT"
  dbname: "oth_product_code"
  charset: "utf8mb4"

redis:
  host: localhost
  port: 6379
  password: "0608"
  db: 0 

